In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from scipy.stats import chi2_contingency, fisher_exact

1.Load data & Data Overview

In [45]:
df = pd.read_excel("../data/2022Cdata.xlsx")

In [46]:
print(df.shape)
df.info()
df.head(10)

(58, 5)
<class 'pandas.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   文物编号    58 non-null     int64
 1   纹饰      58 non-null     str
 2   类型      58 non-null     str
 3   颜色      54 non-null     str
 4   表面风化    58 non-null     str
dtypes: int64(1), str(4)
memory usage: 2.4 KB

   文物编号 纹饰  类型  颜色 表面风化
0     1  C  高钾  蓝绿  无风化
1     2  A  铅钡  浅蓝   风化
2     3  A  高钾  蓝绿  无风化
3     4  A  高钾  蓝绿  无风化
4     5  A  高钾  蓝绿  无风化
5     6  A  高钾  蓝绿  无风化
6     7  B  高钾  蓝绿   风化
7     8  C  铅钡   紫   风化
8     9  B  高钾  蓝绿   风化
9    10  B  高钾  蓝绿   风化

2. Missing Value

In [47]:
df.isnull().sum()

文物编号    0
纹饰      0
类型      0
颜色      4
表面风化    0
dtype: int64

3. Value counts

In [48]:
for col in ["类型","纹饰","颜色","表面风化"]:

        print("="*20)
        print(col)
        print(df[col].value_counts(dropna=False))

====================
类型
类型
铅钡    40
高钾    18
Name: count, dtype: int64
====================
纹饰
纹饰
C    30
A    22
B     6
Name: count, dtype: int64
====================
颜色
颜色
浅蓝     20
蓝绿     15
深绿      7
紫       4
NaN     4
浅绿      3
深蓝      2
黑       2
绿       1
Name: count, dtype: int64
====================
表面风化
表面风化
风化     34
无风化    24
Name: count, dtype: int64

In [49]:
print(df.columns)

Index(['文物编号', '纹饰', '类型', '颜色', '表面风化'], dtype='str')

## 1. Cross-tabulation between Glass Type and Weathering

Purpose:
To summarize the frequency distribution of weathering status under different glass types.

In [50]:
table_type_display=pd.crosstab( 
    df["类型"], df["表面风化"] , margins=True)
table_type

表面风化  无风化  风化  All
类型
铅钡     12  28   40
高钾     12   6   18
All    24  34   58

In [51]:
table_type=pd.crosstab( 
    df["类型"], df["表面风化"] )
table_type

表面风化  无风化  风化
类型
铅钡     12  28
高钾     12   6

In [52]:
chi2_contingency?

Signature: chi2_contingency(observed, correction=True, lambda_=None, *, method=None)
Docstring:
Chi-square test of independence of variables in a contingency table.

This function computes the chi-square statistic and p-value for the
hypothesis test of independence of the observed frequencies in the
contingency table [1]_ `observed`.  The expected frequencies are computed
based on the marginal sums under the assumption of independence; see
`scipy.stats.contingency.expected_freq`.  The number of degrees of
freedom is (expressed using numpy functions and attributes)::

    dof = observed.size - sum(observed.shape) + observed.ndim - 1

Parameters
----------
observed : array_like
    The contingency table. The table contains the observed frequencies
    (i.e. number of occurrences) in each category.  In the two-dimensional
    case, the table is often described as an "R x C table".
correction : bool, optional
    If True, *and* the degrees of freedom is 1, apply Yates' correction
    for continuity.  The effect of the correction is to adjust each
    observed value by 0.5 towards the corresponding expected value.
lambda_ : float or str, optional
    By default, the statistic computed in this test is Pearson's
    chi-squared statistic [2]_.  `lambda_` allows a statistic from the
    Cressie-Read power divergence family [3]_ to be used instead.  See
    `scipy.stats.power_divergence` for details.
method : ResamplingMethod, optional
    Defines the method used to compute the p-value. Compatible only with
    ``correction=False``,  default `lambda_`, and two-way tables.
    If `method` is an instance of `scipy.stats.PermutationMethod` or
    `scipy.stats.MonteCarloMethod`, the p-value is computed using
    `scipy.stats.permutation_test`/`scipy.stats.monte_carlo_test` with the
    provided configuration options and other appropriate settings.
    Otherwise, the p-value is computed as documented in the notes.
    Note that if `method` is an instance of `scipy.stats.MonteCarloMethod`, the
    ``rvs`` attribute must be left unspecified; Monte Carlo samples are always drawn
    using the ``rvs`` method of `scipy.stats.random_table`.

    .. versionadded:: 1.15.0

Returns
-------
res : Chi2ContingencyResult
    An object containing attributes:

    statistic : float
        The test statistic.
    pvalue : float
        The p-value of the test.
    dof : int
        The degrees of freedom. NaN if `method` is not ``None``.
    expected_freq : ndarray, same shape as `observed`
        The expected frequencies, based on the marginal sums of the table.

See Also
--------

:func:`scipy.stats.contingency.expected_freq`
    ..
:func:`scipy.stats.fisher_exact`
    ..
:func:`scipy.stats.chisquare`
    ..
:func:`scipy.stats.power_divergence`
    ..
:func:`scipy.stats.barnard_exact`
    ..
:func:`scipy.stats.boschloo_exact`
    ..
:ref:`hypothesis_chi2_contingency`
    Extended example


Notes
-----
An often quoted guideline for the validity of this calculation is that
the test should be used only if the observed and expected frequencies
in each cell are at least 5.

This is a test for the independence of different categories of a
population. The test is only meaningful when the dimension of
`observed` is two or more.  Applying the test to a one-dimensional
table will always result in `expected` equal to `observed` and a
chi-square statistic equal to 0.

This function does not handle masked arrays, because the calculation
does not make sense with missing values.

Like `scipy.stats.chisquare`, this function computes a chi-square
statistic; the convenience this function provides is to figure out the
expected frequencies and degrees of freedom from the given contingency
table. If these were already known, and if the Yates' correction was not
required, one could use `scipy.stats.chisquare`.  That is, if one calls::

    res = chi2_contingency(obs, correction=False)

then the following is true::

    (res.statistic, res.pvalue) == stats.chisquare(obs.ravel(),
                                                   f_exp=ex.ravel(),
                                                   ddof=obs.size - 1 - dof)

The `lambda_` argument was added in version 0.13.0 of scipy.

References
----------
.. [1] "Contingency table",
       https://en.wikipedia.org/wiki/Contingency_table
.. [2] "Pearson's chi-squared test",
       https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test
.. [3] Cressie, N. and Read, T. R. C., "Multinomial Goodness-of-Fit
       Tests", J. Royal Stat. Soc. Series B, Vol. 46, No. 3 (1984),
       pp. 440-464.

Examples
--------
A two-way example (2 x 3):

>>> import numpy as np
>>> from scipy.stats import chi2_contingency
>>> obs = np.array([[10, 10, 20], [20, 20, 20]])
>>> res = chi2_contingency(obs)
>>> res.statistic
2.7777777777777777
>>> res.pvalue
0.24935220877729619
>>> res.dof
2
>>> res.expected_freq
array([[ 12.,  12.,  16.],
       [ 18.,  18.,  24.]])

Perform the test using the log-likelihood ratio (i.e. the "G-test")
instead of Pearson's chi-squared statistic.

>>> res = chi2_contingency(obs, lambda_="log-likelihood")
>>> res.statistic
2.7688587616781319
>>> res.pvalue
0.25046668010954165

A four-way example (2 x 2 x 2 x 2):

>>> obs = np.array(
...     [[[[12, 17],
...        [11, 16]],
...       [[11, 12],
...        [15, 16]]],
...      [[[23, 15],
...        [30, 22]],
...       [[14, 17],
...        [15, 16]]]])
>>> res = chi2_contingency(obs)
>>> res.statistic
8.7584514426741897
>>> res.pvalue
0.64417725029295503

When the sum of the elements in a two-way table is small, the p-value
produced by the default asymptotic approximation may be inaccurate.
Consider passing a `PermutationMethod` or `MonteCarloMethod` as the
`method` parameter with `correction=False`.

>>> from scipy.stats import PermutationMethod
>>> obs = np.asarray([[12, 3],
...                   [17, 16]])
>>> res = chi2_contingency(obs, correction=False)
>>> ref = chi2_contingency(obs, correction=False, method=PermutationMethod())
>>> res.pvalue, ref.pvalue
(0.0614122539870913, 0.1074)  # may vary

For a more detailed example, see :ref:`hypothesis_chi2_contingency`.
File:      /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/scipy/stats/contingency.py
Type:      function

In [53]:
result=chi2_contingency(
    table_type, 
    correction=False)
result

Chi2ContingencyResult(statistic=np.float64(6.8803921568627455), pvalue=np.float64(0.008714644061182652), dof=1, expected_freq=array([[16.55172414, 23.44827586],
       [ 7.44827586, 10.55172414]]))

In [54]:
print("Chi-square stastistic :", result.statistic )
print("p-value:",result.pvalue)
print( "degree of freedom:" , result.dof)
print("expected frequency:",result.expected_freq)

Chi-square stastistic : 6.8803921568627455
p-value: 0.008714644061182652
degree of freedom: 1
expected frequency: [[16.55172414 23.44827586]
 [ 7.44827586 10.55172414]]

In [55]:
expected = pd.DataFrame(
    result.expected_freq,
    index=table_type.index,
    columns=table_type.columns
)

expected

表面风化        无风化         风化
类型
铅钡    16.551724  23.448276
高钾     7.448276  10.551724

In [56]:
print("Minimum expected frequency:", expected.min().min())

Minimum expected frequency: 7.448275862068965

### Chi-square Assumption Check

All expected frequencies are greater than 5.

Therefore, the assumptions of the Pearson Chi-square test are satisfied.

Since p-value < 0.05,

the null hypothesis of independence is rejected.

Therefore,

glass type and weathering status are significantly associated.